django_e/uzr_auth/basic_opr_app/urls.py
from django.conf.urls import url 
from basic_opr_app import views

app_name = 'basic_opr_app'

urlpatterns = [
    url(r'^register$',views.register,name='register'),
    url(r'^uzr_login',views.uzr_login,name='uzr_login')
]

django_e/uzr_auth/uzr_auth/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_opr_app import views
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'special/',views.special,name='special'),
    url(r'^logout/$',views.uzr_logout,name='logout'),
    url(r'^basic_opr_app/',include('basic_opr_app.urls')),
    url(r'^admin/', admin.site.urls),
]

django_e/uzr_auth/basic_opr_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class user_profile_model(models.Model):
    user = models.OneToOneField(User)
    # additiaonal classes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pics',blank=True) #پروفایل پیکس  همان ساب دایرکتوری هست که باید فایل ها رو بفرسته

    def __str__(self):
        return self.user.username
        #user با حرف کوچیک یعنی از توی one to one میاد
        # حالا pillow رو توی محیط نصب میکنیم
        # تا بتونیماز عکس استفاده کنیم
                

'''pip install pillows'''

django_e/uzr_auth/basic_opr_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_opr_app.models import user_profile_model

class User_reg_form(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    # تمام وییت ها آبجکت های متدی هستن که ریترن میشن
    # پس پرانتز دارن
    class Meta():
        model = User # دوباره از خود اوزر اثلی باحرف بزرگ گرفتیم
        fields= ('username','email','password')
# اینجا یدونه مدل فرم از خود یوزر ساختیم اما نمیدونم چرا دو فرم جدا از هم ساختیم و آیا یوزر حالا که 
# به صورت one to one با کلاس ما رابطه داره  آیا همین فرم به هر دو پر مدل یوزر و مدل 
# one to one شده از یوزر تبعیت میکنه یا نه
class user_profile_set_form(forms.ModelForm):
    class Meta():
        model = user_profile_model
        fields = ('portfolio_site','profile_pic')

django_e/uzr_auth/basic_opr_app/views.py
from django.shortcuts import render
from basic_opr_app.forms import user_profile_set_form,User_reg_form
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect , HttpResponse
from django.contrib.auth import login , logout , authenticate








def index(request):
    return render ( request,'basic_opr_app/index.html')







@login_required
def uzr_logout(request):
    print('bfor lgout')
    logout(request)
    print ('log out ?')
    return HttpResponseRedirect(reverse('index'))






@login_required
def special(request):
    return HttpResponse(' آفرین به شما که لاگین کردید ')







def register(request):
    registered = False
    # return render ( request,'basic_opr_app/index.html')
    if request.method =="POST":
        # registered = False
        
        user_form = User_reg_form(data=request.POST)
        profile_form = user_profile_set_form(data=request.POST)
        # =====================================================
        if user_form.is_valid() and profile_form.is_valid():
            
            user =user_form.save()
            user.set_password(user.password)
            user.save()
            # ===========
            profile = profile_form.save(commit=False)
            profile.user = user
            # ===========
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            # ===========
            profile.save()
            registered =True
            # continue
        #     return render(request,'basic_opr_app/register.html',{
        #     'ins_form_reg':user_form,
        #     'ins_form_profile':profile_form,
        #     'registered':registered
        # })
        # دفعه اول ریترن رو زیر else نوشتم من uuuuu
        else: # NOT VALID
            print(user_form.errors,profile_form.errors)
            print("============================================")
            print("============== ERR ERR ERR =================")
            print("============================================")
        
        # ===============
    else: # REQUEST IS GET
        user_form = User_reg_form()
        profile_form = user_profile_set_form()
    return render(request,'basic_opr_app/register.html',{
        'ins_form_reg':user_form,
        'ins_form_profile':profile_form,
        'registered':registered
    })












def uzr_login (request):
    if request.method == 'POST':
        print('############################# post #############################')
        username = request.POST.get('username')

        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user :
            print('############################# uzr #############################')
            
            if user.is_active: # is_active is not function
                print('############################# akt #############################')

                login(request,user)  # here the user is logged in now
                print('############################# success #############################')

                return HttpResponseRedirect(reverse('index')) #https://docs.djangoproject.com/en/2.2/ref/urlresolvers/
                # why use reverse
            else:
                print('############################# no akt #############################')

                return HttpResponse('این اکانت فعال نیست ')
        else:
            print('############################# no valid #############################')
            return HttpResponse(' اطلاعات شما برای لاگین درست نیست ')
    else:
        print('############################# no post #############################')
        return render(request,'basic_opr_app/login.html',{})

django_e/uzr_auth/templates/basic_opr_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Material Design Bootstrap</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <style>
  body{
    font-size: 1.5em;
  }
  </style>
</head>

<body>


<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark secondary-color fixed-top">

    <!-- Navbar brand -->
    <a class="navbar-brand" href="{% url 'index' %}">تمرین لاگ این و رجیستر </a>
  
    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
      aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="basicExampleNav">
  
      <!-- Links -->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item btn   ">
          <a class="nav-link" href="{% url 'index' %}">خانه 
            <!-- <span class="sr-only">(current)</span> -->
          </a>
        </li>
        <li class="nav-item btn  ">
          <a class="nav-link" href="{% url 'basic_opr_app:register' %}">ثبت نام </a>
        </li>
        <!-- <li class="nav-item btn  ">
          <a class="nav-link" href="{% url 'basic_opr_app:uzr_login' %}">ورود به حساب </a>
        </li> -->

        {% if user.is_authenticated %}

        <li class="nav-item btn  ">
          <a class="nav-link" href="{% url 'logout' %}">خروج از حساب </a>
        </li>
        <li class="nav-item btn  ">
          <a class="nav-link" href="{% url 'special' %}">ویژه</a>
        </li>
        <!-- <li class="nav-item btn  ">
          <img src="" alt="" >
        </li> -->

        {% else %}
        <li class="nav-item btn  ">
          <a class="nav-link" href="{% url 'basic_opr_app:uzr_login' %}">ورود به حساب </a>
        </li>
        {% endif %}
        <!-- Dropdown -->
        <!-- <li class="nav-item btn   dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li> -->
  
      </ul>
      <!-- Links -->
  
      <form class="form-inline">
        <div class="md-form my-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        </div>
      </form>
    </div>
    <!-- Collapsible content -->
  
  </nav>
  <!--/.Navbar-->
  <div style="margin: 6em"></div>
<div class="container text-right" dir="rtl">

  <!-- Start your project here-->
    {% block body_block %}
    {% endblock %}
  <!-- Start your project here-->

</div>


  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
</body>

</html>

django_e/uzr_auth/templates/basic_opr_app/index.html
{% extends 'basic_opr_app/base.html' %}

{% block body_block%}



<h1>به سایت آزمایشی من خوش آمدید</h1>

{% endblock %}

django_e/uzr_auth/templates/basic_opr_app/login.html
{% extends 'basic_opr_app/base.html' %}

{% block body_block%}



<h1> صفحه ی ورود به حساب کاربری</h1>
<p></p>



    
    <!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

        <!-- Material form login -->
<div class="col-lg-6">
<div class="card ">

    <h5 class="card-header  white-text secondary-color text-center py-4">
      <strong>Sign in</strong>
    </h5>
  
    <!--Card content-->
    <div class="card-body px-lg-5 pt-0">
  
      <!-- Form -->
      <form class="text-center" style="color: #757575;" action="{% url 'basic_opr_app:uzr_login' %}" method="POST">
        {% csrf_token %}
        <!-- user name -->
        <div class="md-form">
          <input type="text" id="materialLoginFormEmail" class="form-control" name="username">
          <label for="materialLoginFormEmail">نام کاربری</label>
        </div>
  
        <!-- Password -->
        <div class="md-form">
          <input type="password" id="materialLoginFormPassword" class="form-control" name="password">
          <label for="materialLoginFormPassword">رمز عبور</label>
        </div>
  
        <div class="d-flex justify-content-around">
          <!-- <div> -->
            <!-- Remember me -->
            <!-- <div class="form-check">
              <input type="checkbox" class="form-check-input" id="materialLoginFormRemember">
              <label class="form-check-label" for="materialLoginFormRemember">Remember me</label>
            </div>
          </div>
          <div> -->
            <!-- Forgot password -->
             <!-- <a href="">Forgot password?</a>
          </div> -->
        </div>

        <!-- Sign in button -->
        <button class="btn btn-outline-secondary  btn-rounded btn-block my-4 waves-effect z-depth-0" type="submit">ورود</button>
  
        <!-- Register
        <p>Not a member?
          <a href="">Register</a>
        </p>
   -->
        <!-- Social login -->
        <!-- <p>or sign in with:</p>
        <a type="button" class="btn-floating btn-fb btn-sm">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a type="button" class="btn-floating btn-tw btn-sm">
          <i class="fab fa-twitter"></i>
        </a>
        <a type="button" class="btn-floating btn-li btn-sm">
          <i class="fab fa-linkedin-in"></i>
        </a>
        <a type="button" class="btn-floating btn-git btn-sm">
          <i class="fab fa-github"></i>
        </a> -->
  
      
      <!-- Form -->
  
    </div>
  
  </div>
  <!-- Material form login -->
</div>
    <!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
</form>


{% endblock %}

django_e/uzr_auth/templates/basic_opr_app/register.html
{% extends 'basic_opr_app/base.html' %}

{% block body_block%}



{% if registered %}
    <h1>از ثبت نام شما ممنونیم</h1>
{% else %}

<h1> در اینجا ثبت نام کنید</h1>
<h3>این فرم را پر کنید</h3>

<form  method="POST" enctype="multipart/form-data">

    <!-- چون داریم عکس میگیریم از طرف باید اینکریپشن کنیم -->
    <!-- ENC TYPE multi part form data  -->
    {% csrf_token %}
    {{ ins_form_reg.as_p }}
    {{ ins_form_profile.as_p }}
    <input type="submit" value="ثبت نام">
</form>
{% endif %}
{% endblock %}