djagno_F/class_based_views/basic/urls.py
from django.conf.urls import url 
from . import views

app_name = 'basic'
urlpatterns=[
    url(r'^$',views.school_list_view.as_view(),name = 'list'),
    url(r'^(?P<pk>[-\w]+)/$',views.school_detail_view.as_view(),name='detail'),
    # url(r'^(?P<pk>[-\w]+)/$)',views.students_list_view.as_view(),name='students'),
    # سوال خیلی جالب اینه که چطوری میشه بریم یه ویوی دیگه برای دانش آموزای این مدرسه درست 
    # کردس
    url(r'^create/$',views.create_school_view.as_view(),name='create'),
]

djagno_F/class_based_views/class_based_views/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$',views.index, name = 'index' ),
    # url(r'^$',views.CBV_idx.as_view()), # برای نرمال ویوها بود
    url(r'^$',views.temp_cbv_idx.as_view(),name = 'index'),
     # همون تمپلیت اولی رو ریترن کرد 
    url(r'^basic/', include('basic.urls',namespace = 'basic')),
     # نکته ی جدید برای این اینه که از namespace استفاده میکنیم
]

djagno_F/class_based_views/basic/models.py
from django.db import models

# Create your models here.
# حالا یک مدل تستی برای مدرسه و مدیر میسازیم
class school(models.Model):
    name = models.CharField(max_length=100)
    principal = models.CharField(max_length = 100 )
    location = models.CharField(max_length = 300 )
    
    def __str__(self):
        return self.name

class student ( models.Model):
    name = models.CharField(max_length = 100 )
    age = models.PositiveIntegerField()
    school = models.ForeignKey(school,related_name = 'students')
    def __str__(self):
        return self.name


# حالا کمی از اینا در ادمین استفاده میکنیم
# و یک سوپر یوزر میسازیم

djagno_F/class_based_views/basic/views.py
from . import models
from django.http import HttpResponse
from django.views.generic import (View,TemplateView,ListView,DetailView,
                                  CreateView,DeleteView,UpdateView)
from django.shortcuts import render


# def index(request):
    # return render(request,'basic./index.html')

# class CBV_idx(View):
#     #  for getting method we have get method
#     def get(self,request):
#         return HttpResponse('<h1> سلام سلام بچه ها گل های خوب و زیبا  </h1>')
#         # این ویو فقط برای ویو هایی هست که قراره هیچ تمپلیتی رو نشون ندن و فقط 
#         # یک اچ تی پی ریسپانس نشون بدن
#         # برای ویو های دیگه از تمپلیت ویو ها استفاده مییشه


class temp_cbv_idx(TemplateView):
    template_name = 'basic/index.html' # اینجا هم باید یک یو آر ال داده بشه برحسب تمپلیت ویو ها
    # حالا برای کانتکست فرستادنش داریم
    def get_context_data(self,**kwargs): # *args برای تعداد المنت های توی پرانتز به کار میاد ولی

        '''# def foo(*args):
            # for a in args :
            #     print (a)
            # A خودکار از 1 شروع میشود
        # foo(1,2,4,9)
        # foo (1)
        # **kwargs برای  دیکشنری دادن به کار میاد
        # def bar(**kwargs):
            # for a in kwargs:
                # print (a, kwargs[a])
        # bar( name = "mohammad",age=21 )
        '''
        context = super().get_context_data(**kwargs)
        context['ins_msg'] = 'سلام از کانتکست داخل تمپلیت ویو'
        return context
        # اینم از نحوه ی استفاده از  کانتکست ویو باید زیاد تمرین بشه
#  حالا نحوه ی استفاده از ویو های کراد 
        
# که اکثر این ویو ها برای مدل ها تعریف میشه که 
# اتوماتیک تمام کارهای اصلی رو انجام میده برای نمایش و کانتکست وغیره
# قبلا با 
# Model.objects.all()----> context array 
# نمایش میدادیم ولی الان با استفاده از ویوهای خیلی خفن نمایش میدیم
#  این ویو ها انقدر توی جنگو مورد استفاده هستند که اصن کلاس خودشونو دارن
#  وreverse که یعنی هر تمپلتی داخل خود اپ باشه نه توی فولدر عمومی تمپلت 

                # THE REVERSE BEST PRACTICE
                # --------------------------
                

# حالا نوبت این رسیده که از کانونشن ریورس استفاده کنیم
# این یعنی که هر اپی برای خودش تمپلیت ویو داشته باشد و نه این که هر اپی در 
# فولدر تمپلیت اصلی یک ساب فولدر داشته باشد

# ======== in rooot ========
# ├───basic  ---------------> فولدر اپ
# │   ├───migrations
# │   │   └───__pycache__
# │   ├───templates --------> فولدر کانونشن تمپلیت ( new )
# │   │   └───basic --------> فولدر هم اسم اپ ( new )
# │   └───__pycache__
# ├───class_based_views
# │   └───__pycache__
# └───templates ------------> تمپلیت های عمومی
#     └───basic
 

class school_list_view (ListView):
    # here we connect the model
    model = models.school
    # and only this
    # و کانتکست رو خودش از روی مدل میسازه به این صورت که اسم مدل رو
    # به انتهای اون اضافه میکنه کلمه ی لیست رو با آندر اسکور
    # context = modelName_list
    # و برای اور راید کردن این تنظیمات از این خصیص استفاده میکنیم
    context_object_name = 'schools'

class school_detail_view (DetailView):
    model = models.school
    context_object_name = 'school_detail'
    template_name = 'basic/school_detail.html'

class students_list_view(ListView):
    model = models.school
    context_object_name = 'schools_data'


# داستان create view
# برای ساختن create view
#  باید اولن توجه داشت که نیازی به دادن آدرس تمپلیت نیست
# خودش توی ارور میگه که فلان تمپلیت رو پیدا نکرده و عین اونو میسازیم
# و اگر خواستیم تغییر میدیم با پراپرتی های خودش

class create_school_view(CreateView):
    fields =('name','principal','location')
    model = models.school

djagno_F/class_based_views/basic/templates/basic/basic_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bootstrap link  -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% if page_name %}
    <title> {{ page_name }} </title>
    {% else %}
    <title> صفحه اصلی  </title>
    {% endif %}
</head>
<!-- body here ------------------------------------------------------------------------- -->
<body>

    <!-- nav bar here ------------------------------------------------------------------------- -->
          <nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="font-size: 1.5em">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'index' %}">خانه  <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link btn-lg btn-outline-success" href="{% url 'basic:list' %}">لیست مدارس </a>
                </li>
                <!-- <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                  </div>
                </li> -->
                <!-- <li class="nav-item">
                  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li> -->
              </ul>
              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Search</button>
              </form>
            </div>
          </nav>
    <!-- /nav bar here ------------------------------------------------------------------------- -->
    <!-- spacer here ------------------------------------------------------------------------- -->
        <div style="margin:4.5em">
        </div>
    <!-- /spacer here ------------------------------------------------------------------------- -->

    <!-- container here ------------------------------------------------------------------------- -->
        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>
    <!-- /container here ------------------------------------------------------------------------- -->
<!-- all js files here ------------------------------------------------------------------------- -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<!-- /body here ------------------------------------------------------------------------- -->
</body>
</html>

djagno_F/class_based_views/basic/templates/basic/school_detail.html
{% extends 'basic/basic_base.html' %}

{% block body_block %}

    <h1>سلام خیلی خیلی خوش آمدید</h1>
    <h3>  توضیحات مدرسه <strong > {{ school_detail.name }}</strong></h3>
<!-- 
    <h3>{{ school_detail.name }}</h3> -->
    <p></p>
    <div style="border: 1px solid lightblue">     </div>
<p></p>
    <h3>{{ school_detail.principal }} : نام مدیر</h3>
    <h3>{{ school_detail.location }} : مکان مدرسه</h3>
    <div style="margin: 1.7em"></div>
    <h3>لیست دانش آموزان</h3>
    <p></p>
   <!-- { % for student in school_detail.students % } غلط -->
   <!-- {% for student in school_detail.students.all %} 
    <div style="border: 1px solid lightblue">     </div>
    <h4><li>{{ student.name }}</li></h4>
    <p></p>
    {% endfor %} -->
    <a href="{{ school.id }}">
    <button type="button" class="btn btn-outline-info btn-lg"> مشاهده ی لیست دانش آموزان</button></a>
<p></p>
    <div style="border: 1px solid lightblue">     </div>
    <p></p>
    <a href="{% url 'basic:list' %}">
    <button type="button" class="btn btn-outline-info btn-lg">بازگشت به لیست</button></a>
{% endblock %}

djagno_F/class_based_views/basic/templates/basic/school_form.html
{% extends 'basic/basic_base.html' %}

{% block body_block %}

<h1> سلام در اینجا لیستی از مدارس را میبینید</h1>

{% if not form.instace.pk %}

create school

{% else %}

update school

{% endif %}
 
<form action="" method="post">

    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="" id="" value="ارسال">
</form>

{% endblock %}

djagno_F/class_based_views/basic/templates/basic/school_list.html
{% extends 'basic/basic_base.html' %}

{% block body_block %}

<h1> سلام در اینجا لیستی از مدارس را میبینید</h1>

{% for school in schools %}

 <h3><li> <a href="{{ school.id }}">{{ school }}</a></li></h3>

{% endfor %}


{% endblock %}